config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'addresses/' => 'addresses#index'
  post 'addresses/' => 'addresses#create'
  get 'addresses/new' => 'addresses#new', as: :new_address
  get 'addresses/:id' => 'addresses#show', as: :address
  get 'addresses/:id/edit' => 'addresses#edit', as: :edit_address
  put 'addresses/:id' => 'addresses#update'
  patch 'addresses/:id' => 'addresses#update'
  delete 'addresses/:id' => 'addresses#destroy'

  resources :users
  post 'signup' => 'users#create'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'













  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  validates_presence_of :loc
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord
  validates :email, presence: true, uniqueness:true
  include BCrypt

  has_many :addresses, dependent: :destroy
  has_secure_password

  def password=(new_password)
		@password = Password.create(new_password)
		self.password_digest = @password
	end

  def password
		@password ||= Password.new(password_digest)
	end
end

app/controllers/address_controller.rb
class AddressController < ApplicationController

    def index
      @addresses = Address.all
    end

    def show
    end

    def new
      @address = Address.new
    end

    def create
      @address = Address.new(address_params)

      if @address.save
        redirect_to @address
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @address.update_attributes(address_params)
        redirect_to @address
      else
        render :edit
      end
    end

    def destroy
      @address.destroy
      redirect_to addresses_path
    end

  private
    def address_params
      params.require(:address).permit(:loc, :label, :memo, :balance, :total_rec, :total_sent, :total_fees)
    end

    def set_address
      @address = address.find(params[:id])
    end
  end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  before_action :set_address, only: [:show, :edit, :update, :destroy]
    def index


      @user = User.find_by(id: session[:user_id])
      @addresses = @user.addresses
    end

    def show
      begin
      @response = HTTParty.get('https://blockchain.info/address/'+@address.loc+'?format=json')
      @BTC = @response.parsed_response['final_balance']/100000000.0
      @total_received = @response.parsed_response['total_received']/100000000.0
      @total_sent = @response.parsed_response['total_sent']/100000000.0
    rescue
      @BTC = "Invalid Address"
    end


    end



    def new
      @address = Address.new
      @user_id = session[:user_id]
    end

    def create
      @address = Address.new(address_params)
        @address.user_id = session[:user_id]

      if @address.save

        redirect_to action: "show", id: @address.id
      else
        flash.now[:error] = @address.errors.full_messages.to_sentence.sub! "Loc", "Address"
        render :new
      end
    end

    def edit

    end

    def update

      if @address.update_attributes(address_params)
        redirect_to @address
      else
        render :edit
      end
    end

    def destroy
      @address.destroy
      redirect_to addresses_path
    end

  private
    def address_params
      params.require(:address).permit(:loc, :label, :memo, :balance, :total_rec, :total_sent, :total_fees)
    end

    def set_address
      @address = Address.find(params[:id])
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

    @user = User.new
  end

  def create

    @user = User.find_by(email: params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id.to_s
      redirect_to users_path
    else
      @user = User.new
      flash.now[:alert] = "Password and/or Email Incorrect"
      render :new


    end
  end

  def destroy
    session.delete :user_id
    redirect_to login_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    def index
      @users = User.all
    end

    def show
      if @user != User.find(session[:user_id])
        redirect_to users_path
      end
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id.to_s
        redirect_to users_path
      else
        render :new
      end
    end

    def edit
      if @user != User.find(session[:user_id])
        redirect_to users_path
      end
    end

    def update
      if @user.update_attributes(user_params)
        redirect_to @user
      else
        render :edit
      end
    end

    def destroy
      @user.destroy
      redirect_to new_user_path
    end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def set_user
      @user = User.find(params[:id])
    end
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]



    def index
      @users = User.all
    end

    def show
      if @user != User.find(session[:user_id])
        redirect_to users_path
      end
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id.to_s
        redirect_to users_path
      else
        render :new
      end
    end

    def edit
      if @user != User.find(session[:user_id])
        redirect_to users_path
      end
    end

    def update
      if @user.update_attributes(user_params)
        redirect_to @user
      else
        render :edit
      end
    end

    def destroy
      @user.destroy
      redirect_to new_user_path
    end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def set_user
      @user = User.find(params[:id])
    end
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  #login error handling with before_action
  def logged_in?
      !current_user.nil?
  end

  # Confirms a logged-in user.
  def logged_in_user
     unless logged_in?
        flash[:danger] = "Please log in." #
        redirect_to login_url
     end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/address/index.html.erb
<h1>My Bitcoin Addresses</h1>

<ul>
  <% @addresses.each do |address| %> 
    <li>
      <%= link_to address.name.capitalize, address_path(address) %>
      <%= link_to 'Edit', edit_address_path(address) %>
      <%= link_to 'Delete', address, method: :delete, data: {confirm: 'Are you sure?'} %>
    </li>
  <% end %>
</ul>

<%= link_to 'Add a new address', new_address_path %>

app/views/address/show.html.erb
<h1><%= @address.label.capitalize %></h1>

<table>
  <thead>
    <td>
      Label:
    </td>
    <td>
      Address:
    </td>
    <td>
      Memo:
    </td>
    <td>
      Cool?
    </td>
  </thead>
  <tbody>
    <td>
      <%= @address.label %>
    </td>
    <td>
      <%= @address.loc %>
    </td>
    <td>
      $<%= @address.memo %>
    </td>
  </tbody>
</table>

app/views/addresses/_form.html.erb
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash alert  alert-success" %>
<% end %>



<%= form_for @address do |f| %>

  <div class="container">
  <div class="form-group">
    <label>Label: </label>
    <%= f.text_field :label, :class=>"form-control" %>
  </div>

  <div class="form-group">
    <label>Address: </label>
    <%= f.text_field :loc, :class=>"form-control" %>
  </div>

  <div class="form-group">
    <label>Memo:</label>
    <%= f.text_field :memo, :class=>"form-control" %>
  </div>

  <div>
  <%= f.submit  class: "btn btn-default" %>
  </div>
</div>
<% end %>

app/views/addresses/edit.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
       <a class="navbar-brand">BTC Manager</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to "Home", users_path %>
        <li> <%= link_to "My Addresses", addresses_path %>
        <li> <%= link_to 'Log Out', logout_path, method: :delete %> </li>

      </ul>
    </div>
  </div>
</nav>

<div class="container">
<div class="page-header">
<h1>Edit Address</h1>
</div>
<div class="jumbotron">
<%= render 'form' %>


</div>
</div>

app/views/addresses/index.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
       <a class="navbar-brand">BTC Manager</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
          <li> <%= link_to "Home", users_path %> </li>
          <li><%= link_to 'Add New Address', new_address_path %></li>
      <li> <%= link_to 'Log Out', logout_path, method: :delete %> </li>

      </ul>
    </div>
  </div>
</nav>


<div class="container">

<div class="page-header">
  <h1>My Bitcoin Addresses</h1>
</div>
  <div class="jumbotron">

<% @addresses.each do |address| %>
  <ul class="list-group">
  <li class="list-group-item">  <%= link_to address.label.capitalize, address_path(address) %> <span class="badge" >




      <%= link_to 'Edit', edit_address_path(address) %>
      <%= link_to 'Delete', address, method: :delete, data: {confirm: 'Are you sure?'} %>
  <p class="copy-address" data-clipboard-text=<%= address.loc %>> Copy </p> </span></li>
</ul>
  <% end %>
</div>
</div>

<script>
  $(document).ready(function() {
    var clip = new ZeroClipboard($(".copy-address"))
    clip.on("aftercopy", function(event) {
    $('#myModal').modal('show');
    })
  });


</script>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">

      <div class="modal-body">
        Address Copied!
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/addresses/new.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
       <a class="navbar-brand">BTC Manager</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to "Home", users_path %>
        <li> <%= link_to "My Addresses", addresses_path %>
        <li> <%= link_to 'Log Out', logout_path, method: :delete %> </li>

      </ul>
    </div>
  </div>
</nav>

<div class="container">
<div class="page-header">
  <h1>New Bitcoin Address</h1>
</div>
<div class="jumbotron">




<%= render 'form' %>
</div>
</div>

app/views/addresses/show.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
       <a class="navbar-brand">BTC Manager</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
            <li> <%= link_to "Home", users_path %></li>
            <li><%= link_to 'Add New Address', new_address_path %></li>
            <li> <%= link_to "My Addresses", addresses_path %></li>
            <li> <%= link_to 'Edit Address', edit_address_path %> </li>
            <li> <%= link_to 'Delete Address', address_path, method: :delete, data: {confirm: 'Are you sure?'} %>
            <li> <%= link_to 'Log Out', logout_path, method: :delete %> </li>


      </ul>
    </div>
  </div>
</nav>

<div class="container">
<h1><%= @address.label.capitalize %><img class="qrCode" src='https://blockchain.info/qr?data=<%= @address.loc %>'></h1>


<table class="table">
  <thead>
    <tr>
      <th>Address</th>
      <th>Balance</th>
    </tr>
  </thead>
  <tbody>
  <tr>
    <td>
      <%= link_to @address.loc, "https://blockchain.info/address/#{@address.loc}" %>
    </td>
    <td>
  <%= number_with_delimiter(@BTC, :delimiter => ',') %>
    </td>
</tr>
  </tbody>
</table>

<table class="table">
  <thead>
    <tr>
      <th>Total Sent</th>
    </tr>
  </thead>
  <tbody>
  <tr>
    <td>
      <%= number_with_delimiter(@total_sent, :delimiter => ',') %>
    </td>
</tr>
  </tbody>
</table>

<table class="table">
  <thead>
    <tr>
      <th>Total Received</th>
    </tr>
  </thead>
  <tbody>
  <tr>
    <td>
      <%= number_with_delimiter(@total_received, :delimiter => ',') %>
    </td>
</tr>
  </tbody>
</table>
</div>
<div class="container">
  <div class="page-header">
    <h1>Info</h1>
  </div>
  <%= @address.memo %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BTCManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/_form.html.erb
<%= form_for @user do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/user/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.name %>
    </li>
  <% end %>
</ul>

<% if current_user %>
  Logged in as: <%= current_user.name %> | <%= link_to 'Log Out', logout_path, method: :delete %>
<% else %>
  <%= link_to 'Log In', login_path %>
  <%= link_to 'Sign Up', new_user_path %>
<% end %>


<%

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

<div class="container">
<div class="jumbtron">
  <div class="form-group">
    <label>Name:</label>
    <%= f.text_field :name, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <label>Email:</label>
    <%= f.text_field :email, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <label>Password:</label>
    <%= f.password_field :password, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <label>Password Confirmation:</label>
    <%= f.password_field :password_confirmation, :class=>"form-control" %>
  </div>
  <div>
    <%= f.submit 'Sign up', :class=>"btn btn-default"   %>
  </div>
</div>
</div>

<% end %>

app/views/users/edit.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
       <a class="navbar-brand">BTC Manager</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to "Home", users_path %>
        <li> <%= link_to "My Addresses", addresses_path %>
        <li> <%= link_to 'Log Out', logout_path, method: :delete %> </li>

      </ul>
    </div>
  </div>
</nav>


<div class="container">
    <h1>Edit My Info</h1>
<div class="jumbotron">

  <%= form_for @user do |f| %>
  <div class="form-group">

    <label>Name</label>
    <%= f.text_field :name, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <label>Email</label>
    <%= f.text_field :email, :class=>"form-control" %>
  </div>

  <div>
    <%= f.submit 'Update Info', :class=>"btn btn-default"   %>
  </div>
<% end %>
</div>
</div>

app/views/users/index.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
       <a class="navbar-brand">BTC Manager</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      <li> <%= link_to 'Log Out', logout_path, method: :delete %> </li>
      </ul>
    </div>
  </div>
</nav>


<div class="jumbotron text-center">

<h1>Welcome!</h1>

<% if current_user %>
<p>  You are logged in as: <%= current_user.name %>  </p>
<% else %>
  <%= link_to 'Log In', login_path %>
  <%= link_to 'Sign Up', new_user_path %>
<% end %>

  <div class="container">
<div class="well well-sm">

<%= link_to 'Add A New Address', new_address_path %> |
<%= link_to 'View My Addresses', addresses_path %> |
<%= link_to 'Edit My Info', edit_user_path(current_user) %> |
<%= link_to 'Delete My Account', user_path(current_user), method: :delete, data: {confirm: "are you sure?"} %>
</div>
</div>
</div>

app/views/users/new.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
       <a class="navbar-brand">BTC Manager</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">

        <li> <%= link_to "Bitcoin Addresses?", "https://en.bitcoin.it/wiki/Address" %>
        <li><%= link_to 'Log In', login_path %></li>

      </ul>

    </div>
  </div>
</nav>

<div class="container">
  <div class="jumbotron text-center">
    <h1>BTC Manager</h1>
    <p>Store your Bitcoin addresses!  Keep track of your balances!</p>
  </div>
</div>

<div class="container">
<div class="jumbotron">
  <h1>Sign Up!</h1>
<%= render 'form' %>
</div>
</div>

app/views/users/show.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
       <a class="navbar-brand">BTC Manager</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      <li> <%= link_to 'Log Out', logout_path, method: :delete %> </li>
      </ul>
    </div>
  </div>
</nav>

<div class="jumbotron text-center">

<h1>Welcome!</h1>

<% if current_user %>
<p>  You are logged in as: <%= current_user.name %>  </p>
<% else %>
  <%= link_to 'Log In', login_path %>
  <%= link_to 'Sign Up', new_user_path %>
<% end %>
<div class="container">
<div class="well well-sm">

<%= link_to 'Add A New Address', new_address_path %> |
<%= link_to 'View My Addresses', addresses_path %> |
<%= link_to 'Edit My Info', edit_user_path(current_user) %> |
<%= link_to 'Delete My Account', user_path(current_user), method: :delete, data: {confirm: "are you sure?"} %>
</div>
</div>
</div>

app/views/welcome/index.html.erb
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
       <a class="navbar-brand">BTC Manager</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

        <li> <%= link_to "Bitcoin Addresses?", "https://en.bitcoin.it/wiki/Address" %></li>
        <li><%= link_to 'Log In', login_path %></li>
        <li><%= link_to 'Sign Up', new_user_path %></li>




      </ul>

    </div>
  </div>
</nav>



<div class="container">
  <div class="jumbotron text-center">
  <img src="btc.png" />
    <h1>BTC Manager</h1>
    <p>Store your Bitcoin addresses!  Keep track of your balances!</p>
  </div>
</div>



<div class="navbar navbar-default navbar-fixed-bottom">
    <div class="container">
      <p class="navbar-text pull-left">© 2016 - Site Built By Aaron Goldsmith
      </p>
    <ul class="nav navbar-nav navbar-right">

        <li><a href="https://www.linkedin.com/in/aaron-goldsmith-41a55976" class="btn btn-block btn-social btn-linkedin">
            <span class="fa fa-linkedin"></span>
              </a></li>
        <li><a href="https://github.com/AaronJGoldsmith" class="btn btn-block btn-social btn-github">
              <span class="fa fa-github"></span>
              </a></li>
        <li><a href="https://twitter.com/AaronGold81" class="btn btn-block btn-social btn-twitter">
              <span class="fa fa-twitter"></span>
              </a></li>
        <li><a href="https://www.instagram.com/coldcrushforce/" class="btn btn-block btn-social btn-instagram">
              <span class="fa fa-instagram"></span>
              </a></li>
      <ul>
    </div>










<!-- <div class="welcome">
<div class="container">


<div class="col-md-6">
<div class="jumbotron text-center">
<%= link_to 'Log In', login_path %>

</div>
</div>
<div class="col-md-6">
<div class="jumbotron text-center">



<%= link_to 'Sign Up', new_user_path %>


</div>
</div>
</div>
</div> -->